version: 0.2
phases:
  install:
  pre_build:
    commands:
      - apt-get update
      - apt-get install -y jq
      - wget https://corretto.aws/downloads/resources/17.0.9.8.1/amazon-corretto-17.0.9.8.1-linux-x64.tar.gz
      - mv amazon-corretto-17.0.9.8.1-linux-x64.tar.gz ../
      - tar xzf ../amazon-corretto-17.0.9.8.1-linux-x64.tar.gz -C ../  
      - export PATH=../amazon-corretto-17.0.9.8.1-linux-x64/bin:$PATH
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006.zip
      - mv ./sonar-scanner-cli-5.0.1.3006.zip ../
      - unzip ../sonar-scanner-cli-5.0.1.3006.zip -d ../
      - pwd
      - ls -l
      - export PATH=$PATH:../sonar-scanner-cli-5.0.1.3006/bin/
  build:
    commands:
      - echo 1234
      - sonar-scanner -Dsonar.organization=ravneetsh -Dsonar.projectKey=housing-portal -Dsonar.host.url=https://sonarcloud.io/ -Dsonar.token=d1f802aa42beba6e13fca6ec1d0fe3d4b0751c3d -Dsonar.sources=.
      - sleep 5
      - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=$Project >result.json
      - cat result.json
      - if [ $(jq -r '.projectStatus.status' result.json) = ERROR ] ; then $CODEBUILD_BUILD_SUCCEEDING -eq 0 ;fi