# Generated by Django 2.1.15 on 2023-11-01 23:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('housingapp', '0002_auto_20231101_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houseadvertisement',
            name='nearest_landmark',
        ),
        migrations.AddField(
            model_name='houseadvertisement',
            name='nearby_utility_landmarks',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
