# Generated by Django 2.1.15 on 2023-11-01 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housingapp', '0003_auto_20231101_2333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='houseadvertisement',
            old_name='nearby_utility_landmarks',
            new_name='nearby_utilities_landmarks',
        ),
    ]
