# Generated by Django 2.1.15 on 2023-12-08 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housingapp', '0004_auto_20231101_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseadvertisement',
            name='address',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='houseadvertisement',
            name='contact_no',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='houseadvertisement',
            name='number_of_bathroom',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='houseadvertisement',
            name='number_of_bedroom',
            field=models.PositiveIntegerField(),
        ),
    ]
