# Generated by Django 2.1.15 on 2023-12-08 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housingapp', '0005_auto_20231208_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseadvertisement',
            name='contact_no',
            field=models.CharField(max_length=20),
        ),
    ]
